cask "font-akoni-nerd-font" do
  version "1.2.1"
  sha256 "f19d417a25017260195177f260a390ba1d7633dfd82dc8da142ce96011ea18dd"

  url "https://github.com/cdevoogd/akoni/releases/download/v#{version}/akoni-nerd-font-#{version}.zip"
  name "Akoni Nerd Font"
  desc "Akoni patched with the Nerd Fonts patcher to add a high number of glyphs"
  homepage "https://github.com/cdevoogd/akoni"

  font "AkoniNerdFont-Bold.ttf"
  font "AkoniNerdFont-BoldItalic.ttf"
  font "AkoniNerdFont-BoldOblique.ttf"
  font "AkoniNerdFont-ExtraBold.ttf"
  font "AkoniNerdFont-ExtraBoldItalic.ttf"
  font "AkoniNerdFont-ExtraBoldOblique.ttf"
  font "AkoniNerdFont-ExtraLight.ttf"
  font "AkoniNerdFont-ExtraLightItalic.ttf"
  font "AkoniNerdFont-ExtraLightOblique.ttf"
  font "AkoniNerdFont-Heavy.ttf"
  font "AkoniNerdFont-HeavyItalic.ttf"
  font "AkoniNerdFont-HeavyOblique.ttf"
  font "AkoniNerdFont-Italic.ttf"
  font "AkoniNerdFont-Light.ttf"
  font "AkoniNerdFont-LightItalic.ttf"
  font "AkoniNerdFont-LightOblique.ttf"
  font "AkoniNerdFont-Medium.ttf"
  font "AkoniNerdFont-MediumItalic.ttf"
  font "AkoniNerdFont-MediumOblique.ttf"
  font "AkoniNerdFont-Oblique.ttf"
  font "AkoniNerdFont-Regular.ttf"
  font "AkoniNerdFont-SemiBold.ttf"
  font "AkoniNerdFont-SemiBoldItalic.ttf"
  font "AkoniNerdFont-SemiBoldOblique.ttf"
  font "AkoniNerdFont-Thin.ttf"
  font "AkoniNerdFont-ThinItalic.ttf"
  font "AkoniNerdFont-ThinOblique.ttf"
end
