cask "font-akoni-nerd-font" do
  version "1.0.0"
  sha256 "4e0901dd840c96437c1c66a71f0f783d24481b32c17faed9743de1e9a6b2bd5b"

  url "https://github.com/cdevoogd/akoni/releases/download/v#{version}/akoni-nerd-font-#{version}.zip"
  name "Akoni Nerd Font"
  desc "Akoni patched with the Nerd Fonts patcher to add a high number of glyphs"
  homepage "https://github.com/cdevoogd/akoni"

  font "Akoni Extended Nerd Font Complete.ttf"
  font "Akoni Extended Nerd Font Complete Bold.ttf"
  font "Akoni Extended Nerd Font Complete Bold Italic.ttf"
  font "Akoni Extended Nerd Font Complete Bold Oblique.ttf"
  font "Akoni Extended Nerd Font Complete ExtraBold.ttf"
  font "Akoni Extended Nerd Font Complete ExtraBold Italic.ttf"
  font "Akoni Extended Nerd Font Complete ExtraBold Oblique.ttf"
  font "Akoni Extended Nerd Font Complete ExtraLight.ttf"
  font "Akoni Extended Nerd Font Complete ExtraLight Italic.ttf"
  font "Akoni Extended Nerd Font Complete ExtraLight Oblique.ttf"
  font "Akoni Extended Nerd Font Complete Heavy.ttf"
  font "Akoni Extended Nerd Font Complete Heavy Italic.ttf"
  font "Akoni Extended Nerd Font Complete Heavy Oblique.ttf"
  font "Akoni Extended Nerd Font Complete Italic.ttf"
  font "Akoni Extended Nerd Font Complete Light.ttf"
  font "Akoni Extended Nerd Font Complete Light Italic.ttf"
  font "Akoni Extended Nerd Font Complete Light Oblique.ttf"
  font "Akoni Extended Nerd Font Complete Medium.ttf"
  font "Akoni Extended Nerd Font Complete Medium Italic.ttf"
  font "Akoni Extended Nerd Font Complete Medium Oblique.ttf"
  font "Akoni Extended Nerd Font Complete Oblique.ttf"
  font "Akoni Extended Nerd Font Complete SemiBold.ttf"
  font "Akoni Extended Nerd Font Complete SemiBold Italic.ttf"
  font "Akoni Extended Nerd Font Complete SemiBold Oblique.ttf"
  font "Akoni Extended Nerd Font Complete Thin.ttf"
  font "Akoni Extended Nerd Font Complete Thin Italic.ttf"
  font "Akoni Extended Nerd Font Complete Thin Oblique.ttf"
  font "Akoni Nerd Font Complete.ttf"
  font "Akoni Nerd Font Complete Bold.ttf"
  font "Akoni Nerd Font Complete Bold Italic.ttf"
  font "Akoni Nerd Font Complete Bold Oblique.ttf"
  font "Akoni Nerd Font Complete ExtraBold.ttf"
  font "Akoni Nerd Font Complete ExtraBold Italic.ttf"
  font "Akoni Nerd Font Complete ExtraBold Oblique.ttf"
  font "Akoni Nerd Font Complete ExtraLight.ttf"
  font "Akoni Nerd Font Complete ExtraLight Italic.ttf"
  font "Akoni Nerd Font Complete ExtraLight Oblique.ttf"
  font "Akoni Nerd Font Complete Heavy.ttf"
  font "Akoni Nerd Font Complete Heavy Italic.ttf"
  font "Akoni Nerd Font Complete Heavy Oblique.ttf"
  font "Akoni Nerd Font Complete Italic.ttf"
  font "Akoni Nerd Font Complete Light.ttf"
  font "Akoni Nerd Font Complete Light Italic.ttf"
  font "Akoni Nerd Font Complete Light Oblique.ttf"
  font "Akoni Nerd Font Complete Medium.ttf"
  font "Akoni Nerd Font Complete Medium Italic.ttf"
  font "Akoni Nerd Font Complete Medium Oblique.ttf"
  font "Akoni Nerd Font Complete Oblique.ttf"
  font "Akoni Nerd Font Complete SemiBold.ttf"
  font "Akoni Nerd Font Complete SemiBold Italic.ttf"
  font "Akoni Nerd Font Complete SemiBold Oblique.ttf"
  font "Akoni Nerd Font Complete Thin.ttf"
  font "Akoni Nerd Font Complete Thin Italic.ttf"
  font "Akoni Nerd Font Complete Thin Oblique.ttf"
end
