cask "font-akoni" do
  version "1.2.1"
  sha256 "621e965a91a936938f3968fc7915aeea04191b0b7a57194fed4e8c7346645da5"

  url "https://github.com/cdevoogd/akoni/releases/download/v#{version}/akoni-#{version}.zip"
  name "Akoni"
  desc "A custom build of the Iosevka typeface"
  homepage "https://github.com/cdevoogd/akoni"

  font "akoni-bold.ttf"
  font "akoni-bolditalic.ttf"
  font "akoni-boldoblique.ttf"
  font "akoni-extrabold.ttf"
  font "akoni-extrabolditalic.ttf"
  font "akoni-extraboldoblique.ttf"
  font "akoni-extralight.ttf"
  font "akoni-extralightitalic.ttf"
  font "akoni-extralightoblique.ttf"
  font "akoni-heavy.ttf"
  font "akoni-heavyitalic.ttf"
  font "akoni-heavyoblique.ttf"
  font "akoni-italic.ttf"
  font "akoni-light.ttf"
  font "akoni-lightitalic.ttf"
  font "akoni-lightoblique.ttf"
  font "akoni-medium.ttf"
  font "akoni-mediumitalic.ttf"
  font "akoni-mediumoblique.ttf"
  font "akoni-oblique.ttf"
  font "akoni-regular.ttf"
  font "akoni-semibold.ttf"
  font "akoni-semibolditalic.ttf"
  font "akoni-semiboldoblique.ttf"
  font "akoni-thin.ttf"
  font "akoni-thinitalic.ttf"
  font "akoni-thinoblique.ttf"
end
