# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranches < Formula
  desc "An alternative to `git branch` with some extra information."
  homepage "https://github.com/cdevoogd/git-branches"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.4.0/git-branches_Darwin_x86_64.tar.gz"
      sha256 "5425d196acb38b0c8080c1465f2f733b11a55670c7c2113eec44be9ead45fbf9"

      def install
        bin.install "git-branches"
      end
    end
    on_arm do
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.4.0/git-branches_Darwin_arm64.tar.gz"
      sha256 "e345ca19cfaaa9e40ae738966b9298fadc0f9f1d80deb5fbbe92f3cd6fc464cd"

      def install
        bin.install "git-branches"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdevoogd/git-branches/releases/download/v0.4.0/git-branches_Linux_x86_64.tar.gz"
        sha256 "9b1a5e6642e35db8168021e81ebac12cb227f186bb47121f1772a70a502617f2"

        def install
          bin.install "git-branches"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdevoogd/git-branches/releases/download/v0.4.0/git-branches_Linux_arm64.tar.gz"
        sha256 "208d0ff02fde79090a8c4560db06a91a3dc151ffaea4f7f01a02e7fa3650109e"

        def install
          bin.install "git-branches"
        end
      end
    end
  end
end
