# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranches < Formula
  desc "An alternative to `git branch` with some extra information."
  homepage "https://github.com/cdevoogd/git-branches"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.3.0/git-branches_Darwin_arm64.tar.gz"
      sha256 "3ee846a3b67753d9eb8ebda224557c5cc6ceeba9c581f53a71fe09b1da740998"

      def install
        bin.install "git-branches"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.3.0/git-branches_Darwin_x86_64.tar.gz"
      sha256 "909a848d3ec5c895f04899fb3eaa5d454bee827234949ddb0c45cc72688beb65"

      def install
        bin.install "git-branches"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.3.0/git-branches_Linux_arm64.tar.gz"
      sha256 "83e89999353cf8be5acf6e432a6c306bbf1aadff4320bdc3c0c8e0cc017747a5"

      def install
        bin.install "git-branches"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.3.0/git-branches_Linux_x86_64.tar.gz"
      sha256 "77c5ef42ba9c2e20e55e404d06fdaa168b82e37476f476af0e0b95b35f41a86a"

      def install
        bin.install "git-branches"
      end
    end
  end
end
