# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBranches < Formula
  desc "An alternative to `git branch` with some extra information."
  homepage "https://github.com/cdevoogd/git-branches"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.1.0/git-branches_Darwin_x86_64.tar.gz"
      sha256 "f38134853702e06b8915e64fcf21433ff716206d368b027440254f773fb3b795"

      def install
        bin.install "git-branches"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.1.0/git-branches_Darwin_arm64.tar.gz"
      sha256 "3722f71edf98ebfdae19cc945bf9dc2a801f27178a103550bc3885fb759da937"

      def install
        bin.install "git-branches"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.1.0/git-branches_Linux_arm64.tar.gz"
      sha256 "fedd3013a1b329866a03004b13797541eb949a7d9df169ec0f3cb890c3438049"

      def install
        bin.install "git-branches"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/git-branches/releases/download/v0.1.0/git-branches_Linux_x86_64.tar.gz"
      sha256 "407a34d7e8b6f6722e323c9d7b64f78645074d1aff415f16f6e8d432bbcd96d3"

      def install
        bin.install "git-branches"
      end
    end
  end
end
