# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notify < Formula
  desc "A tool to send notifications to your phone when a command is complete."
  homepage "https://github.com/cdevoogd/notify"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Darwin_arm64.tar.gz"
      sha256 "80ab9bcfaee49a422a1a95c4867224c3d16c09a10919b4bb3697172e8ecac0ef"

      def install
        bin.install "notify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Darwin_x86_64.tar.gz"
      sha256 "d9f4e360ceca32bffe42bf600c7e6045d2350879066fd86a452f196eedd010a4"

      def install
        bin.install "notify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Linux_arm64.tar.gz"
      sha256 "27fe9349dea9e0159e9db5bc391f7ee51eba1694d322d93e3c5423bfbd0f1090"

      def install
        bin.install "notify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Linux_x86_64.tar.gz"
      sha256 "73fab541a58607105ff6adbc44ffe656d409e2c0cae276d39460262e9789be14"

      def install
        bin.install "notify"
      end
    end
  end
end
