# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notify < Formula
  desc "A tool to send notifications to your phone when a command is complete."
  homepage "https://github.com/cdevoogd/notify"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Darwin_arm64.tar.gz"
      sha256 "237db3827b291d67865d84399fd25267c97691f3a121f095e400a12dea616871"

      def install
        bin.install "notify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Darwin_x86_64.tar.gz"
      sha256 "d11fbcce6c44ae010327239f1429af35ec5d0c004eeb172014b4b1dc1be7f077"

      def install
        bin.install "notify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Linux_x86_64.tar.gz"
      sha256 "1743209d5ca7fc991b280e6d8385a7381c675a387a26ed614d665aa83560e2ff"

      def install
        bin.install "notify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cdevoogd/notify/releases/download/v0.1.0/notify_Linux_arm64.tar.gz"
      sha256 "244b8b336f1876012371480febd96d12614eead7e5d7fbbe3c381a4e290de44e"

      def install
        bin.install "notify"
      end
    end
  end
end
